mysite/mipscode/urls.py
from django.urls import path

from . import views

app_name = 'mipscode'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(),name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),

    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('documentation/<int:pk>/', views.DocumentationView.as_view(), name='documentation'),

    path('ide/', views.IdeView.as_view(), name='ide'),
    path('repository/ide/<int:pk>', views.IdeProjectView.as_view(), name='ideproject'),

    path('repository/', views.RepositoryView.as_view(), name='repository'),
    path('repository/search', views.SearchProjectView.as_view(), name='searchproject'),
    path('repository/<int:pk>/', views.UpdateProjectView.as_view(), name='updateproject'),
    path('repository/<int:pk>/deleting', views.DeleteProjectView.as_view(), name='deleteproject'),
    path('repository/<int:pk>/changefavorite', views.ChangeFavoriteView.as_view(), name='changefavorite'),     

    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),    
    path('tutorials/', views.TutorialsView.as_view(), name='tutorials'),                                                           
    path('tutorials/search', views.SearchTutorialView.as_view(), name='searchtutorial'),
    path('tutorials/create', views.CreateTutorialView.as_view(), name='createtutorial'),
    path('tutorial/<int:pk>', views.OpenTutorialView.as_view(), name='opentutorial'),
]

mysite/mysite/urls.py
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', RedirectView.as_view(url='mipscode/')),                                 
    path('mipscode/', include('mipscode.urls')),
    path('admin/', admin.site.urls),         
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mipscode/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(default='', max_length=150, null=True)
    bio = models.TextField(default='Biografia do Usuário')
    avatar = models.ImageField(
        upload_to='avatar/', default='avatar/default.jpg')

    types_profiles = [
        ('1', 'Admin'),
        ('2', 'Student'),
        ('3', 'Teacher'),
    ]

    user_profile = models.CharField(
        max_length=1, choices=types_profiles, default='2')

    types_themes = [
        ('1', 'Dark'),
        ('2', 'Light'),
    ]

    languages = [
        ('1', 'Português'),
        ('2', 'Inglês'),
    ]

    ide_theme = models.CharField(
        max_length=1, choices=types_themes, default='1')
    language = models.CharField(max_length=1, choices=languages, default='1')
    email_notification = models.BooleanField(default=True)


class Tutorial(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=300)
    content = models.JSONField()
    levels = [
        ('1', 'fácil'),
        ('2', 'médio'),
        ('3', 'dificil'),
    ]

    level = models.CharField(max_length=1, choices=levels, default='1')

    created_at = models.DateTimeField('Created Date', default=timezone.now())

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.data <= now

    def __str__(self):
        return self.title


class Project(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=250)
    favorite = models.BooleanField(default=False)
    content = models.TextField(null=True)
    created_at = models.DateTimeField('Created Date', default=timezone.now())
    edited_at = models.DateTimeField('Edited Date', default=timezone.now())

    def __str__(self):
        return self.title


class Documentation(models.Model):
    title = models.CharField(max_length=50)
    content = models.JSONField(null=True)

    def __str__(self):
        return self.title

mysite/mipscode/views.py
# Importações de autenticação e login
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin

# Importações de gerenciamento de arquivos e imagens
from PIL import Image
from django.core.files.storage import FileSystemStorage

# Importações de views e shortcuts
from django.http import HttpResponseRedirect
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone
from django.views import View
from django.views.generic import TemplateView

# Importações de modelos
from .models import Documentation, Profile, Project, Tutorial

# Outras importações
from json import loads
import uuid
import time

# Importações de gerenciamento de querys
from django.db.models import Q


class IndexView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('mipscode:dashboard'))
        documentation_all = Documentation.objects.all()
        context = {
            "documentationfirst": int(documentation_all.first().pk),
            "title": "inicio"                                                 
        }
        return render(request, "mipscode/index.html", context)


class LoginView(View):
    template_name = 'mipscode/login.html'
    documentation_all = Documentation.objects.all()  

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('mipscode:dashboard'))

        context = {
            "documentationfirst": int(self.documentation_all.first().pk)
        }
        return render(request, self.template_name,context)

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = self._authenticate_user(request, username, password)
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse('mipscode:index'))
        else:        
            context = {
                "documentationfirst": int(self.documentation_all.first().pk),
                'error_message': 'Usuário ou senha incorretos!'}
            return render(request, self.template_name, context)

    def _authenticate_user(self, request, username, password):
        return authenticate(request, username=username, password=password)


class RegistrationView(View):
    template_name = 'mipscode/registration.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        username = request.POST.get('user')
        email = request.POST.get('email')
        password = request.POST.get('password')
        context = {}

        if self._user_exists(email):
            context['error_message'] = 'Já existe uma conta com esse email.'
        else:
            user = self._create_user(username, email, password)
            if user:
                profile = Profile.objects.create(user=user, name=username)
                profile.save()
                return HttpResponseRedirect(reverse('mipscode:login'))
        return render(request, self.template_name, context)

    def _user_exists(self, email):
        return User.objects.filter(email=email).exists()

    def _create_user(self, username, email, password):
        try:
            user = User.objects.create_user(
                username=email, password=password, email=email)
            user.save()
            return user
        except:
            return None


class DocumentationView(View):
    def get(self, request, *args, **kwargs):
        profile = ""
        name = ""
        if request.user.is_authenticated:
            profile = Profile.objects.get(user=request.user)
            name = " ".join(profile.name.split(" ")[:2])
        documentation = get_object_or_404(Documentation, pk=kwargs['pk'])
        documentation_itens = documentation.content

        documentation_all = Documentation.objects.all()
        # next_documentation = 
        context = {
            "name": name,
            "documentation": documentation,
            "documentation_itens": documentation_itens,
            "documentation_all":  documentation_all,
            "title": "documentation",
            "profile": profile,
            "documentationfirst": int(documentation_all.first().pk),
        }

        

        return render(request, "mipscode/documentation.html", context)


class IdeView(View):
    def get(self, request, *args, **kwargs):
        documentation_all = Documentation.objects.all()
        context = {
            "documentationfirst": int(documentation_all.first().pk),
            "title": "ide",}
        return render(request, "mipscode/ide.html", context)


class IdeProjectView(IdeView):
    def get(self, request, *args, **kwargs):
        project = get_object_or_404(Project, pk=kwargs['pk'])
        profile = Profile.objects.get(user=request.user)
        name = " ".join(profile.name.split(" ")[:2])
        documentation_all = Documentation.objects.all()
        context = {
            "profile": profile,
            "title": "ideproject",
            "project": project,
            "name": name,
            "documentationfirst": int(documentation_all.first().pk),
        }

        return render(request, "mipscode/ide.html", context)

    def post(self, request, *args, **kwargs):
        textarea = request.POST.get('content')
        title = request.POST.get('title')
        description = request.POST.get('description')

        Project.objects.filter(pk=kwargs['pk']).update(content=textarea, title=title, description=description, edited_at=timezone.now())
        project = Project.objects.get(pk=kwargs['pk'])
        return HttpResponseRedirect(reverse('mipscode:ideproject', kwargs={'pk': project.pk}))


class DashboardView(View):
    def get(self, request, *args, **kwargs):
        user = request.user
        profile = Profile.objects.get(user=user)
        projects = Project.objects.filter(user=profile).order_by('-edited_at')[:4]
        tutorials_all = Tutorial.objects.all()[:8]
        name = " ".join(profile.name.split(" ")[:2])

        documentation_all = Documentation.objects.all()
        context = {
            "name": name,
            "profile": profile,
            "projects": projects,
            "tutorials_all": tutorials_all,
            "title": "dashboard",
            "now": timezone.now(),
            "documentationfirst": int(documentation_all.first().pk),
        }
        return render(request, "mipscode/dashboard.html", context)

    def post(self, request, *args, **kwargs):
        user = request.user
        profile = Profile.objects.get(user=user)

        title = request.POST.get('title')
        description = request.POST.get('description')
        file = request.POST.get('content_file')

        def handle_uploaded_file(f):
            return f.read().decode()

        if file and file.content_type == 'text/plain':
            content = handle_uploaded_file(file)

        Project.objects.create(user=profile, title=title, description=description,
                               content=content, created_at=timezone.now())

        return HttpResponseRedirect(reverse('mipscode:dashboard'))


class RepositoryView(View):
    def get(self, request, *args, **kwargs):
        title_page = "repository"
        profile = Profile.objects.get(user=request.user)
        name = " ".join(profile.name.split(" ")[:2])
        projects_all = Project.objects.filter(
            user=profile).order_by('-edited_at')
        
        documentation_all = Documentation.objects.all()
        context = {
            'name': name,
            'profile': profile,
            'projects_all': projects_all,
            'title': title_page,
            'documentationfirst': int(documentation_all.first().pk)
            }
        return render(request, "mipscode/repository.html", context)

    def post(self, request, *args, **kwargs):
        user = request.user
        profile = Profile.objects.get(user=user)

        title = request.POST.get('title')
        description = request.POST.get('description')
        file = request.FILES.get('upload')
        content = ""

        def handle_uploaded_file(f):
            return f.read().decode()

        if file and file.content_type == 'text/plain':
            content = handle_uploaded_file(file)

        CreateProject = Project.objects.create(user=profile, title=title, description=description, content=content, created_at=timezone.now(), edited_at=timezone.now())
        return HttpResponseRedirect(reverse('mipscode:ideproject', kwargs={'pk': CreateProject.pk}))

class UpdateProjectView(View):
    def post(self, request, *args, **kwargs):
        title = request.POST.get('title')
        description = request.POST.get('description')
        conteudo = request.POST.get("content")

        project = Project.objects.get(pk=kwargs['pk'])
        
        updated_values = {}
        if title != project.title:
            updated_values['title'] = title
        if description != project.description:
            updated_values['description'] = description
        if conteudo != project.content and conteudo != None:
            updated_values['content'] = conteudo

        Project.objects.filter(pk=project.pk).update(**updated_values, edited_at=timezone.now())
        return HttpResponseRedirect(reverse('mipscode:repository'))

class DeleteProjectView(View):
    def get(self, request, *args, **kwargs):
        project = Project.objects.get(pk=kwargs['pk'])
        project.delete()
        return HttpResponseRedirect(reverse('mipscode:repository'))

class ChangeFavoriteView(View):
    def get(self, request, *args, **kwargs):

mysite/mipscode/templates/mipscode/header.html
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <title>MipsCode</title>
    {% load static %}
    {% block statics %}{% endblock statics %}
    <link rel="stylesheet" href="{% static 'mipscode/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'mipscode/css/geral.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'mipscode/img/logo-mips-min.png' %}">
    
</head>

<body>
    <header class="padding-padrao header-nav">
        <nav class="row navegation align-center">
            <div class="nav-logo row align-center">
                <img src="{% static 'mipscode/img/logo-mips.png' %}" alt="MipsCode Logo" class="logo">
            </div>


            <div class="nav-links">
                {% if user.is_authenticated %}
                {% if title == "dashboard" %}
                <a class="fs-navegations color-green" href="{% url 'mipscode:dashboard' %}">Dashboard</a>
                {% else %}
                <a class="fs-navegations color-gray" href="{% url 'mipscode:dashboard' %}">Dashboard</a>
                {% endif %}

                {% if title == "documentation" %}
                <a class="fs-navegations color-green" href="{% url 'mipscode:documentation' documentationfirst %}">Documentação</a>
                {% else %}
                <a class="fs-navegations color-gray" href="{% url 'mipscode:documentation' documentationfirst %}">Documentação</a>
                {% endif %}

                {% if title == "repository" %}
                <a class="fs-navegations color-green" href="{% url 'mipscode:repository' %}">Repositório</a>
                {% else %}
                <a class="fs-navegations color-gray" href="{% url 'mipscode:repository' %}">Repositório</a>
                {% endif %}

                {% if title == "tutorials" %}
                <a class="fs-navegations color-green" href="{% url 'mipscode:tutorials' %}">Tutoriais</a>
                {% else %}
                <a class="fs-navegations color-gray" href="{% url 'mipscode:tutorials' %}">Tutoriais</a>
                {% endif %}


                {% else %}

                {% if title == "inicio" %}
                <a class="fs-navegations color-green" href="{% url 'mipscode:index' %}">Início</a>
                {% else %}
                <a class="fs-navegations color-gray" href="{% url 'mipscode:index' %}">Início</a>
                {% endif %}

                {% if title == "ide" %}
                <a class="fs-navegations color-green" href="{% url 'mipscode:ide' %}">IDE</a>
                {% else %}
                <a class="fs-navegations color-gray" href="{% url 'mipscode:ide' %}">IDE</a>
                {% endif %} 

                {% if title == "documentation" %}
                <a class="fs-navegations color-green" href="{% url 'mipscode:documentation' documentationfirst %}">Documentação</a>
                {% else %}
                <a class="fs-navegations color-gray" href="{% url 'mipscode:documentation' documentationfirst %}">Documentação</a>
                {% endif %}
                {% endif %}
            </div>

            <div class="nav-buttons">
                {% if user.is_authenticated %}
                <div class="row gap-4">
                    <a class="row align-center gap-1" href="{% url 'mipscode:profile' %}">
                        <div class="avatar" style="background-image: url({{profile.avatar.url}});"></div>
                        <span class="fs-navegations color-white">{{name}}</span>
                    </a>

                    <a href="{% url 'mipscode:logout' %}" class="row align-center"><img class="cursor-pointer"
                            src="{% static 'mipscode/svgs/icon-logout.svg' %}" alt=""></a>
                </div>
                {% else %}
                <a href="{% url 'mipscode:login' %}" class="fs-navegations color-green">Entrar</a>
                <a href="{% url 'mipscode:registration' %}"><input class="fs-navegations button button-white bold"
                        type="button" value="Inscreva-se"></a>
                {% endif %}
            </div>

        </nav>

        <nav class="header-nav-mobile">
            <a href="{% url 'mipscode:dashboard' %}"><img src="{% static 'mipscode/img/logo-mips.png' %}"
                    alt="MipsCode Logo" class="logo"></a>
            <button class="menu" id="button-menu-mobile">
                <img src="{% static 'mipscode/svgs/menu-min.svg' %}" alt="Menu">
            </button>
        </nav>
    </header>

    <div class="menu-mobile padding-padrao" id="menu-mobile-div">
        <button class="menu" id="button-close-mobile">
            <img src="{% static 'mipscode/svgs/menu-min.svg' %}" alt="Menu">
        </button>
        <div class="column gap-2">
            <p class="fs-navegations color-gray bold">MENU</p>
            <div class="nav-buttons">
                {% if user.is_authenticated %}
                <div class="row gap-4">
                    <a class="row align-center gap-1" href="{% url 'mipscode:profile' %}">
                        <div class="avatar" style="background-image: url({{profile.avatar.url}});"></div>
                        <span class="fs-navegations color-white">{{name}}</span>
                    </a>
                </div>
                {% else %}
                <a href="{% url 'mipscode:login' %}" class="fs-navegations color-white">Entrar</a>
                {% endif %}
            </div>
            
            {% if user.is_authenticated %}
            {% if title == "dashboard" %}
            <a class="fs-navegations color-green" href="{% url 'mipscode:dashboard' %}">Dashboard</a>
            {% else %}
            <a class="fs-navegations color-gray" href="{% url 'mipscode:dashboard' %}">Dashboard</a>
            {% endif %}

            {% if title == "documentation" %}
            <a class="fs-navegations color-green" href="{% url 'mipscode:documentation' documentationfirst %}">Documentação</a>
            {% else %}
            <a class="fs-navegations color-gray" href="{% url 'mipscode:documentation' documentationfirst %}">Documentação</a>
            {% endif %}

            {% if title == "repository" %}
            <a class="fs-navegations color-green" href="{% url 'mipscode:repository' %}">Repositório</a>
            {% else %}
            <a class="fs-navegations color-gray" href="{% url 'mipscode:repository' %}">Repositório</a>
            {% endif %}

            {% if title == "tutorials" %}
            <a class="fs-navegations color-green" href="{% url 'mipscode:tutorials' %}">Tutoriais</a>
            {% else %}
            <a class="fs-navegations color-gray" href="{% url 'mipscode:tutorials' %}">Tutoriais</a>
            {% endif %}

            <a href="{% url 'mipscode:logout' %}" class="row align-center color-gray fs-navegations">Logout</a>
            {% else %}

            {% if title == "inicio" %}
            <a class="fs-navegations color-green" href="{% url 'mipscode:index' %}">Início</a>
            {% else %}
            <a class="fs-navegations color-gray" href="{% url 'mipscode:index' %}">Início</a>
            {% endif %}

            {% if title == "ide" %}
            <a class="fs-navegations color-green" href="{% url 'mipscode:ide' %}">IDE</a>
            {% else %}
            <a class="fs-navegations color-gray" href="{% url 'mipscode:ide' %}">IDE</a>
            {% endif %}

            {% if title == "documentation" %}
            <a class="fs-navegations color-green" href="{% url 'mipscode:documentation' documentationfirst %}">Documentação</a>
            {% else %}
            <a class="fs-navegations color-gray" href="{% url 'mipscode:documentation' documentationfirst %}">Documentação</a>
            {% endif %}

            
            {% endif %}
        </div>

    </div>

    {% block article %}{% endblock article %}

    {% if title != "ideproject" and title != "ide" %}
    <footer class="margin-top-7">
        <div class="padding-padrao column ">
            <div class="row top margin-top-7">
                <img class="logo-white" src="{% static 'mipscode/img/logo-mips.png' %}">
                <div class="group">
                    <div class="links column">
                        <h4 class="fs-5 bold">Rotas Principais</h4>
                        <a class="fs-6 color-white ligth" href="{% url 'mipscode:tutorials' %}">Tutorial</a>
                        <a class="fs-6 color-white ligth" href="{% url 'mipscode:documentation' documentationfirst %}">Documentação</a>
                        <a class="fs-6 color-white ligth" href="{% url 'mipscode:repository' %}">Meu Repositório</a>
                    </div>

                    <div class="links column">
                        <h4 class="fs-5 bold">Sobre nós</h4>
                        <a class="fs-6 color-white ligth" href="">Quem Somos</a>
                        <a class="fs-6 color-white ligth" href="">Fale conosco</a>
                        <a class="fs-6 color-white ligth" href="">Termos de Serviços</a>
                    </div>
                </div>
                <div class="links-externs">
                    <img src="{% static 'mipscode/svgs/icon-github.svg' %}">
                    <img src="{% static 'mipscode/svgs/icon-instagram.svg' %}">
                </div>
            </div>
            <div class="fs-6 margin-top-7 bottom">© 2022 MipsCode. Todos os direitos reservados.</div>
        </div>
    </footer>
    {% endif %}
    <script src="{% static 'mipscode/js/interacoes/header.js' %}"></script>
</body>

</html>

mysite/mipscode/templates/mipscode/repository.html
{% extends "mipscode/header.html" %}
{% load static %}
{% load template_filters %}

{% block statics %}
<link rel="stylesheet" href="{% static 'mipscode/css/repositorio.css' %}">
{% endblock statics %}

{% block article %}
<article class="padding-padrao margin-top-2">
    <h1 class="title-local">Meu Repositório</h1>
    <header class="row">
        <p class="color-opaco fs-6 sitemap-inicio margin-zero">Início</p>
        <p class="color-green fs-6 bold margin-zero">Repositório</p>
    </header>


    <section class="column">
        <div class="row content-buttons margin-top-2">
            <button class="button-green color-black background-button-green fs-6 button bold cursor-pointer"
                onclick="openNewProjectView()">
                <img src="{% static 'mipscode/svgs/icons-add.svg' %}">
                <p class="p-button margin-zero">Criar novo arquivo
                <p>
            </button>
        </div>

        <form class="row margin-top-2 justify-space-between div-filters" action="{% url 'mipscode:searchproject' %}"
            method="post">
            {% csrf_token %}
            <input type="text" class="button-white button-background-opaco fs-7 button search"
                placeholder="Buscar arquivo" name="search" value="{{search}}">

            <select name="filters" class="button-white button-background-opaco fs-7 button filters"
                onchange="this.form.submit()">
                <option class="fs-7" value="0" selected="selected" disabled>Filtragem</option>
                <option value="1" class="fs-7">Mais Recentes</option>
                <option value="2" class="fs-7">Mais Antigos</option>
                <option value="3" class="fs-7">Favoritos</option>
            </select>
        </form>

        <div class="content-projetos-all column margin-top-2">
            {% for project in projects_all %}
            <div class="project-div justify-space-between row">
                <div class="column div-projects">
                    <h2 class="fs-4 margin-zero">{{project.title}}</h2>
                    <p class="fs-7 margin-zero color-opaco">{{ project.edited_at|hours_since }}</p>
                    <p class="fs-6 margin-top-1">{{project.description}}</p>
                </div>
                <div class="row options align-center ">
                    <a class="button-white button-background-white fs-7 button"
                        href="{% url 'mipscode:ideproject' project.id%}">Abrir arquivo</a>
                    <div class="row options">
                        {% if project.favorite == True %}
                        <a href="{% url 'mipscode:changefavorite' project.id %}"><img
                                src="{% static 'mipscode/svgs/icon-favoriteTrue.svg' %}"></a>
                        {% else %}
                        <a href="{% url 'mipscode:changefavorite' project.id %}"><img
                                src="{% static 'mipscode/svgs/icon-favorite.svg' %}"></a>
                        {% endif %}

                        <button class="buttonOptions" id="buttonOption{{project.id}}"
                            onclick="openOptions({{project.id}})">
                            <img src="{% static 'mipscode/svgs/icon-options.svg' %}">
                        </button>
                    </div>
                </div>

                <div class="options-div button-background-opaco display-none" id="options-area{{project.id}}">
                    <p class="option color-white fs-6" onclick="openEditar({{project.id}})">Editar</p>
                    <p class="option color-white fs-6">Baixar arquivo</p>
                    <a href="{% url 'mipscode:deleteproject' project.id %}">
                        <p class="option color-red fs-6">Apagar</p>
                    </a>
                </div>
            </div>

            <section class="create-arquivo display-none" id="editar-arquivo{{project.id}}">
                <form class="form-div" action="{% url 'mipscode:updateproject' project.id %}" method="post"
                    enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row justify-space-between align-center">
                        <h1 class="fs-4">Editar Arquivo</h1>

                        <input class="button-close cursor-pointer" id="exit-button" onclick="closeEditar({{project.id}})"
                            type="reset" value="x">
                    </div>

                    <div class="column gap-1 margin-top-2">
                        <input type="text" class="button-white button-background-opaco fs-7 button" name="title"
                            placeholder="Titulo" value="{{project.title}}">
                        <textarea class="button-white button-background-opaco fs-7 textarea button padding-vertical-1"
                            name="description" placeholder="Descrição">{{project.description}}</textarea>

                        <input type="submit" class="button-green color-green button bold cursor-pointer"
                            value="Salvar Mudanças">
                    </div>
                </form>
            </section>
            {% endfor %}


        </div>

    </section>
</article>



<section class="create-arquivo display-none" id="create-arquivo">
    <form class="form-div" action="{% url 'mipscode:repository' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row justify-space-between align-center">
            <h1 class="fs-4">Crie um novo Arquivo</h1>

            <input class="button-close cursor-pointer" id="exit-button" onclick="closeNewProjectView()" type="reset"
                value="x">
        </div>

        <div class="column gap-1 margin-top-2">
            <input type="text" class="button-white button-background-opaco fs-7 button" name="title"
                placeholder="Titulo">
            <textarea class="button-white button-background-opaco fs-7 textarea button padding-vertical-1"
                name="description" placeholder="Descrição"></textarea>
            <div>
                <input type="file" value="Importar arquivo" name="upload" id="file">
                <input type="button" id="fileInput" class="button-white color-white button bold cursor-pointer fs-6"
                    value="Importe um arquivo" onclick="" />
            </div>
            <input type="submit" class="button-green color-green button bold cursor-pointer fs-6" value="Criar Arquivo">
        </div>
    </form>
</section>
<script src="{% static 'mipscode/js/interacoes/projetos.js' %}"></script>

{% endblock article %}